# Generated by Django 4.0.4 on 2022-05-22 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_rename_item_orderitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Product',
            new_name='product',
        ),
    ]
